version: "3"

services:
  nginx:
    image: luke/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: web_nginx_origin
    volumes:
      - ./src:/src
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - php-fpm
    networks:
      vpcbr:
        ipv4_address: 192.168.40.2
  php-fpm:
    image: luke/php-fpm
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: web_php_origin
    volumes:
      - ./src:/src
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - "9000:9000"
    restart: always
    links:
      - mysql-db
      - redis-db
      - memcached-db
      - mongo-db
    networks:
      vpcbr:
        ipv4_address: 192.168.40.3
  mysql-db:
    image: luke/mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: web_mysql_origin
    volumes:
      - ./src:/src
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql/logs:/var/log/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=laravel@2018
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=2018@laravel
    networks:
      vpcbr:
        ipv4_address: 192.168.40.4
  redis-db:
    image: luke/redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: web_redis_origin
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/logs:/var/log/redis
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    ports:
      - "6379:6379"
    restart: always
    networks:
      vpcbr:
        ipv4_address: 192.168.40.5
  memcached-db:
    image: luke/memcached
    build:
      context: ./memcached
      dockerfile: Dockerfile
    container_name: web_memcached_origin
    command: [ "memcached", "-m", "64" ]
    ports:
        - "11211:11211"
    restart: always
    networks:
      vpcbr:
        ipv4_address: 192.168.40.6
  mongo-db:
    image: luke/mongo
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: web_mongo_origin
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongo/data:/data/db
    ports:
        - 27017:27017
    command: ["mongod", "--smallfiles", "--logpath=/dev/null"]
    restart: always
    networks:
      vpcbr:
        ipv4_address: 192.168.40.7

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/24